name: surfacepatcher
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit
  - python=3.12
  - msms
  - pdb2pqr
  - pip
  - pip:
      - torch
      - scipy
      - networkx
      - numpy
      - open3d
      - mdtraj
      - giotto-tda
      - scikit-learn
      - tqdm
      